---
- name: Install prerequisites
  apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

- name: Install Mariadb & MySQL Packages
  apt: name={{ item }} update_cache=yes state=present
  loop: [ 'mysql-server', 'python3-pymysql', ]

- name: Start the MySQL service
  service: 
    name: mysql 
    state: started
    enabled: true


- name: Creates database for WordPress
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ mysql_db }}"
    state: present

- name: Create MySQL user for WordPress
  mysql_user:
    name: "{{ mysql_user }}"
    host: "%"
    password: "{{ mysql_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: "*.*:ALL"
    state: present
   