---
- name: Install prerequisites
  apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

- name: Install Apache
  apt:
    name: apache2
    state: latest

- name: Start Apache & Enabled
  service:
    name: apache2
    state: started
    enabled: yes